export const constants = {
    API_REQUEST : 'API_REQUEST',
    API_SUCCESS : 'API_RETREIVE_SUCCESS',
    API_FAILURE : 'API_RETREIVE_FAILURE',
    API_ID_REQUEST : 'API_ID_REQUEST',
    API_ID_SUCCESS : 'API_ID_RETREIVE_SUCCESS',
    API_ID_FAILURE : 'API_ID_RETREIVE_FAILURE',
    API_PUT_REQUEST : 'API_PUT_ID_REQUEST',
    API_PUT_SUCCESS : 'API_PUT_ID_RETREIVE_SUCCESS',
    API_PUT_FAILURE : 'API_PUT_ID_RETREIVE_FAILURE',
    SERVICE_FAILED : 'API Server Failed!'
}